vich_uploader:
    db_driver: orm



    #mappings:
    #    products:
    #        uri_prefix: /images/sites
    #        upload_destination: '%kernel.project_dir%/public/images/sites'
    mappings:
        sites_images:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         '%app.path.sites_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.sites_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        articles_images:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         '%app.path.articles_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.articles_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        books_images:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         '%app.path.books_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.books_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
